### ISSUE TITLE
init() problem with ST2

### ISSUE THREAD

**Issue by pirackr** [pirackr/Sublime-Bogo#13]
```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 115, in create_text_commands
  File "./sublime-bogo.py", line 139, in __init__
TypeError: super() takes at least 1 argument (0 given)
Traceback (most recent call last):
  File "./sublime_plugin.py", line 115, in create_text_commands
  File "./sublime-bogo.py", line 139, in __init__
TypeError: super() takes at least 1 argument (0 given)
loaded 837 snippets
```

**Comment by pirackr** [comment]
71ad34a23bc9ad6a9711a54f1a573aeca9b5d443
