### ISSUE TITLE
'RuntimeError: maximum recursion depth exceeded' bug

### ISSUE THREAD

**Issue by pirackr** [pirackr/Sublime-Bogo#5]
This  bug appeared when we used the plugin in ST2

**Comment by lewtds** [comment]
Could it be that our own text edit triggers `on_modified` again when we are still processing the previous change?

**Comment by pirackr** [comment]
Yap, that's it, we could see the error log on ST2, I think it's the same problem in both ST2 and ST3.

```
Traceback (most recent call last):
File "./sublime_plugin.py", line 195, in on_modified
File "./sublime_plugin.py", line 154, in run_timed_function
File "./sublime_plugin.py", line 194, in 
File "./set_unsaved_view_name.py", line 14, in on_modified
RuntimeError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
File "./sublime_plugin.py", line 362, in run_
File "./sublime-bogo.py", line 66, in run
File "./bogo/bogo/core.py", line 124, in process_sequence
File "./bogo/bogo/core.py", line 201, in process_key
File "./bogo/bogo/core.py", line 345, in transform
File ".\logging__init_.py", line 1481, in debug
RuntimeError: maximum recursion depth exceeded
Traceback (most recent call last):
File "./sublime_plugin.py", line 195, in on_modified
File "./sublime_plugin.py", line 154, in run_timed_function
File "./sublime_plugin.py", line 194, in 
File "./set_unsaved_view_name.py", line 14, in on_modified
RuntimeError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
File "./sublime_plugin.py", line 362, in run_
File "./sublime-bogo.py", line 66, in run
File "./bogo/bogo/core.py", line 124, in process_sequence
File "./bogo/bogo/core.py", line 201, in process_key
File "./bogo/bogo/core.py", line 345, in transform
File ".\logging__init_.py", line 1481, in debug
RuntimeError: maximum recursion depth exceeded
Traceback (most recent call last):
File "./sublime_plugin.py", line 195, in on_modified
File "./sublime_plugin.py", line 154, in run_timed_function
File "./sublime_plugin.py", line 194, in 
File "./set_unsaved_view_name.py", line 14, in on_modified
RuntimeError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
File "./sublime_plugin.py", line 362, in run_
File "./sublime-bogo.py", line 66, in run
File "./bogo/bogo/core.py", line 124, in process_sequence
File "./bogo/bogo/core.py", line 201, in process_key
File "./bogo/bogo/core.py", line 345, in transform
File ".\logging__init_.py", line 1481, in debug
RuntimeError: maximum recursion depth exceeded
```
